Vagrant.configure("2") do |config|
  # Create/Configure the db vm
  config.vm.define "database" do |database|
    database.vm.box = "ubuntu/bionic64"
    database.vm.network "private_network", ip: "192.168.10.150"
    # db.hostsupdater.aliases = ["database.local"]
    database.vm.synced_folder ".", "/home/vagrant/environment"
    database.vm.provision "shell", path: "environment/db_provision.sh", privileged: false
  end

  # Create/Configure the app vm
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip: "192.168.10.100"
    # app.hostsupdater.aliases = ["development.local"]
    app.vm.synced_folder ".", "/home/vagrant/app"
    app.vm.provision "shell", path: "environment/app_provision.sh", privileged: false
  end


end